services:
  app:
    restart: always
    image: rkllm-openapi:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - STORAGE_PATH=/rkllm
    volumes:
      - ../storage:/rkllm
    #      - ./lib/librkllm_wrapper.so:/usr/lib/librkllm_wrapper.so
    #      - ./lib/librkllmrt.so:/usr/lib/librkllmrt.so
    privileged: true
