/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"os"

	// WARNING!
	// Pass --git-repo-id and --git-user-id properties when generating the code
	//
	"github.com/Tech-Arch1tect/rkllmopenai/config"
	sw "github.com/Tech-Arch1tect/rkllmopenai/go"
	"github.com/Tech-Arch1tect/rkllmopenai/model"
	"github.com/Tech-Arch1tect/rkllmopenai/modelDownload/cmd"
)

func main() {
	if len(os.Args) > 1 {
		cmd.Cmd()
		os.Exit(0)
	}
	config.LoadConfig()
	model.RefreshModelList()
	routes := sw.ApiHandleFunctions{}

	log.Printf("Server started")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
