/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rkllmopenai

type Error struct {
	Type string `json:"type"`

	Message string `json:"message"`

	Param *string `json:"param"`

	Code *string `json:"code"`
}
