/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rkllmopenai

type CreateChatCompletionStreamResponseChoicesInner struct {
	Index int32 `json:"index,omitempty"`

	Delta ChatCompletionStreamResponseDelta `json:"delta,omitempty"`

	FinishReason string `json:"finish_reason,omitempty"`
}
