/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rkllmopenai

type CreateCompletionResponseChoicesInnerLogprobs struct {
	Tokens []string `json:"tokens,omitempty"`

	TokenLogprobs []float32 `json:"token_logprobs,omitempty"`

	TopLogprobs []map[string]interface{} `json:"top_logprobs,omitempty"`

	TextOffset []int32 `json:"text_offset,omitempty"`
}
