/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rkllmopenai

// CreateTranscriptionRequestModel - ID of the model to use. Only `whisper-1` is currently available.
type CreateTranscriptionRequestModel struct {
}
