/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rkllmopenapi

type CreateEmbeddingResponseDataInner struct {

	Index int32 `json:"index"`

	Object string `json:"object"`

	Embedding []float32 `json:"embedding"`
}
