/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package rkllmopenai

type ImagesResponse struct {
	Created int32 `json:"created"`

	Data []ImagesResponseDataInner `json:"data"`
}
